### ISSUE TITLE
Is `enableStaticRendering` needed when used on vercel?

### ISSUE THREAD

**Issue by xieyuheng** [mobxjs/mobx-vue-lite#129]
Like the `enableStaticRendering` of `mobx-react-lite`:

```
import { enableStaticRendering } from "mobx-react-lite"

enableStaticRendering(isServer())
```

**Comment by xieyuheng** [comment]
In `mobx-react-lite` there is a note about SSR environment:

> Call `enableStaticRendering(true)` when running in an SSR environment, in which `observer` wrapped components should never re-render, but cleanup after the first rendering automatically. Use `isUsingStaticRendering()` to inspect the current setting.

Do we need to worry about this when using `mobx-vue-lite`?

If not, why?

(I am new to mobx, want to learn more about this.)

**Comment by iChenLei** [comment]
cc @wobsoriano
