### ISSUE TITLE
The example is not working

### ISSUE THREAD

**Issue by azertyalex** [mobxjs/mobx-vue-lite#3]
I'm trying to use mobx with vue3 but I can't seem to get it working. The example doesn't work either.

**Comment by iChenLei** [comment]
@wobsoriano , look here

**Comment by iChenLei** [comment]
@wobsoriano , look here

**Comment by wobsoriano** [comment]
Hi, there seems to be a problem with the demo link. I'll check. What do you have so far? Vue version? Any repro? Thanks!
